services:
  - type: web
    name: exam-backend
    env: python
    buildCommand: pip install -r python_api/requirements.txt
    startCommand: cd python_api && gunicorn index:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PYTHON_VERSION
        value: 3.11.0
